---
title: "The Key to Winning in America's Pastime"
author: "Scooter Norton & Luke Schleck"
date: "12/02/2024"
format: html
---

```{r setup}
#| include: false

knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
options(width = 100,
        scipen = 999999)

suppressPackageStartupMessages(library(tidyverse))
library(openxlsx)
library(ggplot2)
library(kableExtra)
library(dplyr)
library(car)

practice.question.switch <- "TRUE"
```

## Data Cleaning
```{r}
data <- read_csv("lahman_1871-2023_csv/lahman_1871-2023_csv/Teams.csv")
data <- filter(data, G==162)

baseball_data <- select(data, c('W','AB','H','BB','HR','R','RA','SO','SB','2B','3B','ERA','SHO','SV','HRA','BBA','SOA','CG','FP'))
bd <- baseball_data
bd
```

```{r}
#assigning variable names
wins <- bd$W
at_bats <- bd$AB
hits <- bd$H
walks <- bd$BB
home_runs <- bd$HR
runs <- bd$R
runs_against <- bd$RA
strikeouts <- bd$SO
stolen_bases <- bd$SB
doubles <- bd$'2B'
triples <- bd$'3B'
era <- bd$ERA
shutouts <- bd$SHO
saves <- bd$SV
hr_against <- bd$HRA
walks_against <- bd$BBA
so_b_pitchers <- bd$SOA
cg_b_pitchers <- bd$CG
fielding_percent <- bd$FP

full_model <- lm(wins ~ at_bats + hits + walks + home_runs + runs + runs_against + strikeouts + stolen_bases + doubles + triples + era + shutouts + saves + hr_against + walks_against + so_b_pitchers + cg_b_pitchers + fielding_percent, data=bd)
summary(full_model)
```

```{r}
plot(full_model)
```


```{r}
runs_model <- lm(wins ~ runs + runs_against)
summary(runs_model)
```

```{r}
full_minus_runs_model <- lm(wins ~ at_bats + hits + walks + home_runs + strikeouts + stolen_bases + doubles + triples + shutouts + saves + hr_against + walks_against + so_b_pitchers + cg_b_pitchers, data=bd)
summary(full_minus_runs_model)
```

This model contains all the original variables minus runs, runs_against, era, and fielding percentage

```{r}
plot(full_minus_runs_model)
```


```{r}
backward_stepwise <- step(full_model, direction = "backward")
summary(backward_stepwise)
```


```{r}
forward_stepwise <- step(full_model, direction="forward", scope=full_model)
summary(forward_stepwise)
```

Correlation coefficients for the dataframe using Wins

```{r}
cor(baseball_data$W,baseball_data)
```
For our model, we choose to remove all variables with |correlation coefficient| < 0.2 (very weak/no correlation)

We lose:

* AB
* SO
* SB
* 3B
* SOA
* CG

This leaves us with:

* H
* BB
* HR
* \R
* \RA
* 2B
* \ERA
* SHO
* SV
* HRA
* BBA
* FP

```{r}
model_cor_geq_0.2 <- lm(wins ~ hits + walks + home_runs + doubles + shutouts + saves + hr_against + walks_against + fielding_percent, data=bd)
summary(model_cor_geq_0.2)
```

for abs|cor| > 0.3, we lose:

* HR
* 2B
* HRA
* FP

Which leaves us with:

* H
* BB
* \R
* \RA
* \ERA
* SHO
* SV
* BBA

```{r}
model_cor_geq_0.3 <- lm(wins ~ hits + walks + shutouts + saves + walks_against, data=bd)
summary(model_cor_geq_0.3)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```



